//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodhibelly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.Instructions = new HashSet<Instruction>();
            this.Reviews = new HashSet<Review>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string picture { get; set; }
        public Nullable<System.DateTime> posted { get; set; }
        public Nullable<double> avgrating { get; set; }
        public string description { get; set; }
        public Nullable<int> servings { get; set; }
        public Nullable<int> featured { get; set; }
    
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<Instruction> Instructions { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
